#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR=$SCRIPT_DIR/..

${ROOT_DIR}/node_modules/.bin/nodemon --exec "${ROOT_DIR}/scripts/run_server.sh" --ext iced,coffee --ignore "bundles/*_bundle.iced"
