#!/bin/bash
set -e

# Ubuntu setup script

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR=$SCRIPT_DIR/..

sudo apt-get install nodejs npm
sudo apt-get install mysql-server mysql-client

if [ ! -e "/usr/bin/node" ]; then
    echo "Creating symlink node -> nodejs (used by iced-coffee-script)"
    sudo ln -s nodejs /usr/bin/node
else
    echo "Warning: path to node executable might be wrong"
fi

# TODO: verify this works on a fresh install
sudo mysql -u root -f < scripts/setup_db.sql
